/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import entidades.InfoCli;
import DAO.InfoCliDAO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zEveerY
 */
public class AdminCadastrarInfoCliModal extends java.awt.Dialog {
InfoCli infoCli = new InfoCli();
InfoCliDAO infoCliDAO = new InfoCliDAO();
    
    /**
     * Creates new form AdminCadastrarInfoCliModal
     */
    public AdminCadastrarInfoCliModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jl_cadastrar2 = new javax.swing.JLabel();
        jl_nome2 = new javax.swing.JLabel();
        jl_cnpj2 = new javax.swing.JLabel();
        jl_endereco2 = new javax.swing.JLabel();
        jl_telefone2 = new javax.swing.JLabel();
        jtf_nome2 = new javax.swing.JTextField();
        jtf_cnpj2 = new javax.swing.JTextField();
        jtf_endereco2 = new javax.swing.JTextField();
        jtf_telefone2 = new javax.swing.JTextField();
        jb_save2 = new javax.swing.JButton();
        jb_clear2 = new javax.swing.JButton();
        jb_quit1 = new javax.swing.JButton();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_cadastrar2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_cadastrar2.setText("Cadastrar Informações da Clínica");
        jPanel6.add(jl_cadastrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jl_nome2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_nome2.setText("Nome da Clínica :");
        jPanel6.add(jl_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jl_cnpj2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_cnpj2.setText("C.N.P.J :");
        jPanel6.add(jl_cnpj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jl_endereco2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_endereco2.setText("Endereço :");
        jPanel6.add(jl_endereco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jl_telefone2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_telefone2.setText("Telefone : ");
        jPanel6.add(jl_telefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel6.add(jtf_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));
        jPanel6.add(jtf_cnpj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, -1));
        jPanel6.add(jtf_endereco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, -1));
        jPanel6.add(jtf_telefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, -1));

        jb_save2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jb_save2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/save.png"))); // NOI18N
        jb_save2.setToolTipText("Salvar Dados");
        jb_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_save2ActionPerformed(evt);
            }
        });
        jPanel6.add(jb_save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, -1));

        jb_clear2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jb_clear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clear.png"))); // NOI18N
        jb_clear2.setToolTipText("Limpar Campos");
        jb_clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clear2ActionPerformed(evt);
            }
        });
        jPanel6.add(jb_clear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 170, -1));

        jb_quit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/stop.png"))); // NOI18N
        jb_quit1.setToolTipText("Sair do Sistema");
        jb_quit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_quit1ActionPerformed(evt);
            }
        });
        jPanel6.add(jb_quit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-740)/2, (screenSize.height-445)/2, 740, 445);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jb_save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_save2ActionPerformed
        try {
            valida();
        } catch (SQLException ex) {
            Logger.getLogger(AdminCadastrarInfoCliModal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* try {
            // TODO add your handling code here:
            cadastrar();
        } catch (SQLException ex) {
            Logger.getLogger(AdminCadastrarInfoCli.class.getName()).log(Level.SEVERE, null, ex);
        } */
    }//GEN-LAST:event_jb_save2ActionPerformed

    private void jb_clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clear2ActionPerformed
        // TODO add your handling code here:
        jtf_nome.setText("");
        jtf_cnpj.setText("");
        jtf_endereco.setText("");
        jtf_telefone.setText("");
        Component rootPane = null;

        JOptionPane.showMessageDialog(rootPane, "Campos limpos com sucesso !");
    }//GEN-LAST:event_jb_clear2ActionPerformed

    private void jb_quit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_quit1ActionPerformed
        // TODO add your handling code here:
        //telaAdministrador.valida(false);
        this.dispose();
    }//GEN-LAST:event_jb_quit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminCadastrarInfoCliModal dialog = new AdminCadastrarInfoCliModal(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jb_clear;
    private javax.swing.JButton jb_clear1;
    private javax.swing.JButton jb_clear2;
    private javax.swing.JButton jb_quit;
    private javax.swing.JButton jb_quit1;
    private javax.swing.JButton jb_save;
    private javax.swing.JButton jb_save1;
    private javax.swing.JButton jb_save2;
    private javax.swing.JLabel jl_cadastrar;
    private javax.swing.JLabel jl_cadastrar1;
    private javax.swing.JLabel jl_cadastrar2;
    private javax.swing.JLabel jl_cnpj;
    private javax.swing.JLabel jl_cnpj1;
    private javax.swing.JLabel jl_cnpj2;
    private javax.swing.JLabel jl_endereco;
    private javax.swing.JLabel jl_endereco1;
    private javax.swing.JLabel jl_endereco2;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JLabel jl_nome1;
    private javax.swing.JLabel jl_nome2;
    private javax.swing.JLabel jl_telefone;
    private javax.swing.JLabel jl_telefone1;
    private javax.swing.JLabel jl_telefone2;
    private javax.swing.JTextField jtf_cnpj;
    private javax.swing.JTextField jtf_cnpj1;
    private javax.swing.JTextField jtf_cnpj2;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_endereco1;
    private javax.swing.JTextField jtf_endereco2;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_nome1;
    private javax.swing.JTextField jtf_nome2;
    private javax.swing.JTextField jtf_telefone;
    private javax.swing.JTextField jtf_telefone1;
    private javax.swing.JTextField jtf_telefone2;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() throws SQLException {
        infoCli.setNome_clinica(jtf_nome.getText());
        infoCli.setCnpj(jtf_cnpj.getText());
        infoCli.setEndereco(jtf_endereco.getText());
        infoCli.setTelefone(jtf_telefone.getText());
        
        infoCliDAO.getConnection();
        infoCliDAO.addInfoCli(infoCli);
        
    }

    private void valida() throws SQLException {
        
        if(infoCliDAO.ValidaInfoCli() == true)
        {
            Component rootPane = null;
            JOptionPane.showMessageDialog(rootPane, "Já existe uma clínica cadastrada, os dados foram atualizados");
            //cadastrar();
            updateInfoCli();
        }
        else
        {
            cadastrar();
        }
        
    }

    private void updateInfoCli() throws SQLException {
        
        infoCli.setNome_clinica(jtf_nome.getText());
        infoCli.setCnpj(jtf_cnpj.getText());
        infoCli.setEndereco(jtf_endereco.getText());
        infoCli.setTelefone(jtf_telefone.getText());
        infoCli.setId(1);
        
        //infoCliDAO.getConnection();
        infoCliDAO.updateInfoCli(infoCli);
        
    }
}
