/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.ConvenioDAO;
import entidades.Convenio;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author zEveerY
 */
public class SecAlteraConveniosModal extends java.awt.Dialog {
ConvenioDAO convenioDAO = new ConvenioDAO();
Convenio convenio = new Convenio();
    /**
     * Creates new form SecAlteraConveniosModal
     */
    public SecAlteraConveniosModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jl_cadastrar1 = new javax.swing.JLabel();
        jl_nome1 = new javax.swing.JLabel();
        jl_cpf1 = new javax.swing.JLabel();
        jl_telefone1 = new javax.swing.JLabel();
        jtf_endereco1 = new javax.swing.JTextField();
        jtf_cpf1 = new javax.swing.JTextField();
        jtf_telefone1 = new javax.swing.JTextField();
        jb_save = new javax.swing.JButton();
        jb_clear = new javax.swing.JButton();
        jb_quit = new javax.swing.JButton();
        jl_crm = new javax.swing.JLabel();
        jtf_nome1 = new javax.swing.JTextField();
        jl_crm1 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jl_cadastrar1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_cadastrar1.setText("Alterar Convênios");

        jl_nome1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_nome1.setText("Endereço : ");

        jl_cpf1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_cpf1.setText("C.N.P.J");

        jl_telefone1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_telefone1.setText("Telefone : ");

        jb_save.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jb_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/save.png"))); // NOI18N
        jb_save.setToolTipText("Salvar Dados");
        jb_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveActionPerformed(evt);
            }
        });

        jb_clear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jb_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clear.png"))); // NOI18N
        jb_clear.setToolTipText("Limpar Campos");
        jb_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clearActionPerformed(evt);
            }
        });

        jb_quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/stop.png"))); // NOI18N
        jb_quit.setToolTipText("Sair do Sistema");
        jb_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_quitActionPerformed(evt);
            }
        });

        jl_crm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_crm.setText("Nome : ");

        jl_crm1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_crm1.setText("I.D :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jl_cadastrar1)
                        .addGap(236, 236, 236)
                        .addComponent(jb_quit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_crm1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jl_cpf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_telefone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_crm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_endereco1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_nome1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_telefone1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_id, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_quit)
                    .addComponent(jl_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_crm1)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jb_save)
                        .addGap(83, 83, 83)
                        .addComponent(jb_clear))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_crm)
                            .addComponent(jtf_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_telefone1)
                            .addComponent(jtf_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nome1)
                            .addComponent(jtf_endereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_cpf1)
                            .addComponent(jtf_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jb_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveActionPerformed
        try {
            cadastrar();
        } catch (SQLException ex) {
            Logger.getLogger(AdminCadastrarSecretariasModal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtf_id.setText("");
        jtf_endereco1.setText("");
        jtf_cpf1.setText("");
        jtf_nome1.setText("");
        jtf_telefone1.setText("");
    }//GEN-LAST:event_jb_saveActionPerformed

    private void jb_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clearActionPerformed
        // TODO add your handling code here:
        jtf_endereco1.setText("");
        jtf_cpf1.setText("");
        jtf_nome1.setText("");
        jtf_id.setText("");
        jtf_telefone1.setText("");
        //jpf_senha1.setText("");

        JOptionPane.showMessageDialog(null, "Campos limpos com sucesso !");
    }//GEN-LAST:event_jb_clearActionPerformed

    private void jb_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_quitActionPerformed
        // TODO add your handling code here:
        //telaAdministrador.valida(false);
        this.dispose();
    }//GEN-LAST:event_jb_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SecAlteraConveniosModal dialog = new SecAlteraConveniosModal(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_clear;
    private javax.swing.JButton jb_quit;
    private javax.swing.JButton jb_save;
    private javax.swing.JLabel jl_cadastrar1;
    private javax.swing.JLabel jl_cpf1;
    private javax.swing.JLabel jl_crm;
    private javax.swing.JLabel jl_crm1;
    private javax.swing.JLabel jl_nome1;
    private javax.swing.JLabel jl_telefone1;
    private javax.swing.JTextField jtf_cpf1;
    private javax.swing.JTextField jtf_endereco1;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_nome1;
    private javax.swing.JTextField jtf_telefone1;
    // End of variables declaration//GEN-END:variables
private void cadastrar() throws SQLException {
        //paciente.setCrm(jtf_crm.getText());
        convenio.setId(Integer.parseInt(jtf_id.getText()));
        convenio.setNome(jtf_nome1.getText());
        convenio.setEndereco(jtf_endereco1.getText());
        convenio.setCnpj(jtf_cpf1.getText());
        convenio.setTelefone(jtf_telefone1.getText());
        //paciente.setSenha(jpf_senha1.getText());
        
        //medicosDAO.getConnection();
        convenioDAO.updateConvenio(convenio);
        
        JOptionPane.showMessageDialog(null, "Convênio Atualizado com sucesso !");
        
    }


}