/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JOptionPane;

/**
 *
 * @author zEveerY
 */
public class TelaSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_gerPacientes = new javax.swing.JButton();
        jb_gerConvenios = new javax.swing.JButton();
        jb_gerConsultas = new javax.swing.JButton();
        f_separador = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        jb_gerMedicos = new javax.swing.JButton();
        jb_gerConsultas2 = new javax.swing.JButton();
        jb_gerConsultas3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jb_gerPacientes.setText("Gerenciar Pacientes");
        jb_gerPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerPacientesActionPerformed(evt);
            }
        });

        jb_gerConvenios.setText("Gerenciar Convênios");
        jb_gerConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerConveniosActionPerformed(evt);
            }
        });

        jb_gerConsultas.setText("Gerenciar Consultas");
        jb_gerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerConsultasActionPerformed(evt);
            }
        });

        f_separador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        f_separador.setForeground(new java.awt.Color(153, 153, 153));

        jb_gerMedicos.setText("Gerenciar Médicos");
        jb_gerMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerMedicosActionPerformed(evt);
            }
        });

        jb_gerConsultas2.setText("Agenda Médicas");
        jb_gerConsultas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerConsultas2ActionPerformed(evt);
            }
        });

        jb_gerConsultas3.setText("Emitir Relatórios");
        jb_gerConsultas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerConsultas3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jb_gerConvenios, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .add(jb_gerPacientes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jb_gerMedicos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(38, 38, 38)
                .add(f_separador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jb_gerConsultas2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jb_gerConsultas3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jb_gerConsultas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(jb_gerMedicos)
                .add(39, 39, 39)
                .add(jb_gerPacientes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
                .add(jb_gerConvenios)
                .add(127, 127, 127))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(f_separador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(72, 72, 72)
                .add(jb_gerConsultas)
                .add(36, 36, 36)
                .add(jb_gerConsultas2)
                .add(44, 44, 44)
                .add(jb_gerConsultas3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-550)/2, (screenSize.height-391)/2, 550, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_gerConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerConveniosActionPerformed
        // TODO add your handling code here:
        new SecConvenios().show();
    }//GEN-LAST:event_jb_gerConveniosActionPerformed

    private void jb_gerMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerMedicosActionPerformed
        // TODO add your handling code here:
        new SecMedicos().show();
    }//GEN-LAST:event_jb_gerMedicosActionPerformed

    private void jb_gerConsultas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerConsultas3ActionPerformed
        // TODO add your handling code here:
        new SecEmiteRelatorios().show();
    }//GEN-LAST:event_jb_gerConsultas3ActionPerformed

    private void jb_gerPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerPacientesActionPerformed
        // TODO add your handling code here:
        new SecPacientes().show();
    }//GEN-LAST:event_jb_gerPacientesActionPerformed

    private void jb_gerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerConsultasActionPerformed
        // TODO add your handling code here:
        new SecConsultas().show();
    }//GEN-LAST:event_jb_gerConsultasActionPerformed

    private void jb_gerConsultas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerConsultas2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Não Concluido");
    }//GEN-LAST:event_jb_gerConsultas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSecretaria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler f_separador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_gerConsultas;
    private javax.swing.JButton jb_gerConsultas2;
    private javax.swing.JButton jb_gerConsultas3;
    private javax.swing.JButton jb_gerConvenios;
    private javax.swing.JButton jb_gerMedicos;
    private javax.swing.JButton jb_gerPacientes;
    // End of variables declaration//GEN-END:variables
}
